### ISSUE TITLE
Enhance Android client UI

### ISSUE THREAD

**Issue by kovdan01** [kovdan01/melon#97]
- [x] Add backward arrow button to return from chat to chat list
- [x] Add renaming and deletion of chats
- [x] Add editing and deletion of messages
- [x] Sort chats by last message's send time
- [x] Display each message's send time near it
- [x] Implement read/unread messages feature

**Comment by RomanAnchugov** [comment]
Long click on chat creation btn will automatically generate new chat - made for debug pusposes
